### ISSUE TITLE
Allow profile-validator to accept filepaths as well as URIs of BagIt Profiles

### ISSUE THREAD

**Issue by helrond** [bagit-profiles/bagit-profiles-validator#23]
In order to instantiate a profile, the profile validator currently accepts a URI at which the profile is available (as JSON). I'd like to allow the validator to also accept a filepath at which a profile is available, which would allow me to validate against a profile without going to the trouble of making it available over HTTP.

This _may_ not be in compliance with the Bagit Profiles spec, which seems to state that the profile should be available at a URI, so I'd be interested in hearing from other maintainers whether this is a good idea or not!

**Comment by tdilauro** [comment]
@helrond This is already possible via the `--file FILE` option. For example, you can do something like:
  ```
  bagit_profile.py --file <file-with-profile-json> <uri-of-my-profile> <bag>
  ```
Try `bagit_profile.py --help` for available options.

**Comment by helrond** [comment]
Thanks @tdilauro - obviously I should have checked that first!
